### ISSUE TITLE
.envを読み込み出来ない

### ISSUE THREAD

**Issue by hato72** [hato72/cookmeet-go-backend#6]
/app/src/migrate # GO_ENV=dev go run migrate.goを実行すると

db.goの14行目で引っ掛かり以下のエラーが出る
2024/04/21 06:31:59 Error loading open .env: no such file or directory
exit status 1

**Comment by Moriyuki-S** [comment]
.envファイルってどこに配置してますか？

**Comment by Moriyuki-S** [comment]
もしroot直下に入っていなかったらrootディレクトリ直下にしてみてください。

**Comment by hato72** [comment]
rootにあります

**Comment by hato72** [comment]
コンテナ内からだとenvを取得できないんですかね

**Comment by Moriyuki-S** [comment]
https://zenn.dev/forcia_tech/articles/20230613_hatano_dotenv
こうすればいけるような気がします。

**Comment by hato72** [comment]
backendディレクトリに.env.devをおいたあとにPOSTGRES_PORT=5434 => 5432にして、POSTGRES_HOST=localhost => dbにしたらいけました
